overview:
  activation_strategy: query_param

  next:
    tour_name: "overview"
    controller_name: "services"
    action_name: "index"
    redirect_to: "services_path"
    controller_params:
      tour: overview

  steps:
    0:
      welcome: true
      title: Welcome!
      text: |-
        Welcome to the EOSC Portal Catalogue and Marketplace! We offer services and services to discover, store, share, compose and analyse research data.

        Are you curious to find out how we can support your research?
    1:
      title: Navigation info
      text: |-
        There are different ways to navigate our catalogue.

        Do you want to browse all our services? Then click **Browse through catalogue**

      attachTo:
        element: "[data-shepherd-tour-target='overview_1']"
        placement: "auto"
    2:
      title: Catalogue options
      text: |-
        Want to narrow down the selection to services for your field?
        No problem! Simply click **Scientific Domains** and select the academic field that best describes your work.

        Or are you looking for a specific type of service?
        You can also click **Categories** to filter our catalogue.

      attachTo:
        element: "[data-shepherd-tour-target='overview_2']"
        placement: "auto"
    3:
      title: More catalogue options
      text: |-
        We also offer more **advanced browsing options.** You can use this menu to select services by specific
        
        - **Communities and infrastructures**
        - **Providers**
        - **Target users**
      
      attachTo:
        element: "[data-shepherd-tour-target='overview_3']"
        placement: "auto"
    4:
      title: Browse all services
      text: |-
        Let’s first take a look at the unfiltered view of the catalogue.

      attachTo:
        element: "[data-shepherd-tour-target='overview_4']"
        placement: "auto"
