intro3:
  previous:
    tour_name: "intro2"
    action_name: "edit"
    controller_name: "profiles"
  steps:
    1:
      title: "here we have..."
      text: "user categories..."
      attachTo:
        element: ".home-carousel"
        placement: "bottom"
      buttons:
        1:
          action: 'next'
        2:
          action: 'later'
    2:
      title: "here we have...2"
      text: "user categories...2"
      attachTo:
        element: ".proucts"
        placement: "right"
      buttons:
        1:
          action: 'next'
        2:
          action: 'later'
    3:
      title: "And the end"
      text: "thx"
welcome:
  steps:
    1:
      title: "here we have..."
      text: "user categories..."
      attachTo:
        element: ".categories"
        placement: "top"
      buttons:
        1:
          action: 'next'
        2:
          action: 'later'
    2:
      title: "here we have...2"
      text: "user categories...2"
      attachTo:
        element: ".proucts"
        placement: "right"
      buttons:
        1:
          action: 'next'
        2:
          action: 'later'
    3:
      title: "And the end"
      text: "thx"

