// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutocompleteController from "./autocomplete_controller";
application.register("autocomplete", AutocompleteController);

import CatalogueController from "./catalogue_controller";
application.register("catalogue", CatalogueController);

import ClearerrorsController from "./clearerrors_controller";
application.register("clearerrors", ClearerrorsController);

import ClipboardController from "./clipboard_controller";
application.register("clipboard", ClipboardController);

import ComparisonController from "./comparison_controller";
application.register("comparison", ComparisonController);

import ConversationController from "./conversation_controller";
application.register("conversation", ConversationController);

import DatasourceController from "./datasource_controller";
application.register("datasource", DatasourceController);

import DetailsLoaderController from "./details_loader_controller";
application.register("details-loader", DetailsLoaderController);

import DuplicateController from "./duplicate_controller";
application.register("duplicate", DuplicateController);

import ExitController from "./exit_controller";
application.register("exit", ExitController);

import ExternalController from "./external_controller";
application.register("external", ExternalController);

import FavouriteController from "./favourite_controller";
application.register("favourite", FavouriteController);

import FilterController from "./filter_controller";
application.register("filter", FilterController);

import FormController from "./form_controller";
application.register("form", FormController);

import HomePageController from "./home_page_controller";
application.register("home-page", HomePageController);

import MapController from "./map_controller";
application.register("map", MapController);

import MulticheckboxController from "./multicheckbox_controller";
application.register("multicheckbox", MulticheckboxController);

import OfferController from "./offer_controller";
application.register("offer", OfferController);

import OrderController from "./order_controller";
application.register("order", OrderController);

import OrderingController from "./ordering_controller";
application.register("ordering", OrderingController);

import ParagraphController from "./paragraph_controller";
application.register("paragraph", ParagraphController);

import ParameterController from "./parameter_controller";
application.register("parameter", ParameterController);

import PreviewController from "./preview_controller";
application.register("preview", PreviewController);

import ProjectController from "./project_controller";
application.register("project", ProjectController);

import ProjectItemController from "./project_item_controller";
application.register("project-item", ProjectItemController);

import ProviderController from "./provider_controller";
application.register("provider", ProviderController);

import QuantityPriceController from "./quantity_price_controller";
application.register("quantity-price", QuantityPriceController);

import RemovalsController from "./removals_controller";
application.register("removals", RemovalsController);

import ScrollerController from "./scroller_controller";
application.register("scroller", ScrollerController);

import SearchController from "./search_controller";
application.register("search", SearchController);

import StarsController from "./stars_controller";
application.register("stars", StarsController);

import TokenController from "./token_controller";
application.register("token", TokenController);

import TourfeedbackController from "./tourfeedback_controller";
application.register("tourfeedback", TourfeedbackController);

import TourfeedbackmodalController from "./tourfeedbackmodal_controller";
application.register("tourfeedbackmodal", TourfeedbackmodalController);

import TurboModalController from "./turbo_modal_controller";
application.register("turbo-modal", TurboModalController);
