# frozen_string_literal: true

FactoryBot.define do
  factory :eosc_registry_services_response, class: Hash do
    skip_create
    transient do
      trl { "trl-7" }
      category { "aggregator" }
      tagline { "Large-Scale computing for medical metabolomics" }
    end
    initialize_with do
      # noinspection RubyStringKeysInHashInspection,RubyScope
      next(
        {
          "total" => 154,
          "from" => 0,
          "to" => 3,
          "results" => [
            {
              "service" => {
                "active" => true,
                "suspended" => false,
                "id" => "phenomenal.phenomenal",
                "webpage" => "https://portal.phenomenal-h2020.eu/home",
                "name" => "PhenoMeNal",
                "tagline" => tagline,
                "description" =>
                  "<p>PhenoMeNal (Phenome and Metabolome aNalysis) is a comprehensive and standardised e-infrastructure that supports the data processing and analysis pipelines for molecular phenotype data generated by metabolomics applications.</p>\n",
                "targetUsers" => ["target_user-other"],
                "logo" => "http://phenomenal-h2020.eu/home/wp-content/uploads/2016/06/PhenoMeNal_logo.png",
                "multimedia" => ["https://www.youtube.com/watch?v=-_F8NZwWXew"],
                "resourceOrganisation" => "bluebridge",
                "resourceProviders" => %w[phenomenal phenomenal awesome],
                "version" => "2018.08",
                "lastUpdate" => 1_533_513_600_000,
                "changeLog" => ["fixed bug"],
                "lifeCycleStatus" => "production",
                "trl" => trl,
                "categories" => [{ "category" => "category-data", "subcategory" => "data-applications-software" }],
                "geographicalAvailabilities" => ["WW"],
                "languageAvailabilities" => ["EN"],
                "tags" => ["Metabolomics", "Galaxy", "Workflows", "Cloud Research Environment", "Analytics"],
                "useCases" => ["http://phenomenal-h2020.eu/home/help"],
                "requiredResources" => ["super-service"],
                "relatedResources" => ["extra-service"],
                "order" => "https://portal.phenomenal-h2020.eu/home",
                "helpdeskPage" => "http://phenomenal-h2020.eu/home/help",
                "userManual" => "https://github.com/phnmnl/phenomenal-h2020/wiki",
                "trainingInformation" => "http://phenomenal-h2020.eu/home/training-online",
                "pricing" =>
                  "http://phenomenal-h2020.eu/home/wp-content/uploads/2016/09/Phenomenal-Terms-of-Use-version-11.pdf",
                "paymentModel" => "http://openminted.eu/payment-model",
                "serviceLevel" =>
                  "http://phenomenal-h2020.eu/home/wp-content/uploads/2016/09/Phenomenal-Terms-of-Use-version-11.pdf",
                "termsOfUse" =>
                  "http://phenomenal-h2020.eu/home/wp-content/uploads/2016/09/Phenomenal-Terms-of-Use-version-11.pdf",
                "scientificDomains" => [
                  {
                    "scientificDomain" => "scientific_domain-other",
                    "scientificSubdomain" => "scientific_subdomain-other-other"
                  }
                ],
                "accessTypes" => ["access_type-other"],
                "accessModes" => ["access_mode-other"],
                "resourceGeographicLocations" => ["PL"],
                "mainContact" => {
                  "firstName" => "John",
                  "lastName" => "Doe",
                  "email" => "john@doe.com",
                  "phone" => "+41 678 888 123",
                  "position" => "Developer",
                  "organisation" => "JD company"
                },
                "publicContacts" => [
                  {
                    "firstName" => "Jane 1",
                    "lastName" => "Doe",
                    "email" => "john1@doe.com",
                    "phone" => "",
                    "position" => "",
                    "organisation" => ""
                  },
                  {
                    "firstName" => "Jane 2",
                    "lastName" => "Doe",
                    "email" => "jane2@doe.com",
                    "phone" => "",
                    "position" => "",
                    "organisation" => ""
                  }
                ],
                "helpdeskEmail" => "info@bluebridge.support_for_data_publication",
                "securityContactEmail" => "info@bluebridge.support_for_data_publication",
                "certifications" => ["ISO-639"],
                "standards" => ["standard"],
                "openSourceTechnologies" => ["opensource"],
                "relatedPlatforms" => ["extra-service"],
                "fundingBody" => ["funding_body-other"],
                "fundingPrograms" => ["funding_program-other"],
                "grantProjectNames" => ["grant"],
                "privacyPolicy" => "http://phenomenal-h2020.eu/home/help",
                "accessPolicy" =>
                  "http://phenomenal-h2020.eu/home/wp-content/uploads/2016/09/Phenomenal-Terms-of-Use-version-11.pdf",
                "statusMonitoring" => "http://phenomenal.eu/monit",
                "orderType" => "order_type-other",
                "maintenance" => "http://phenomenal.eu/maintenance"
              },
              "metadata" => {
                "registeredBy" => "John Doe",
                "registeredAt" => "1549033448415",
                "modifiedBy" => "John Doe",
                "modifiedAt" => "1549624107536",
                "source" => "EOSC",
                "originalId" => nil
              },
              "languageAvailabilityNames" => ["English"],
              "geographicAvailabilityNames" => ["Worldwide"],
              "trlName" => "9 - actual system proven in operational environment",
              "phaseName" => nil,
              "lifeCycleStatusName" => "Production",
              "targetUsersNames" => ["Other"],
              "accessTypeNames" => ["Other"],
              "accessModeNames" => ["Other"],
              "fundingBodyNames" => ["Other"],
              "fundingProgramNames" => nil,
              "orderTypeName" => "Other",
              "views" => 15,
              "ratings" => 2,
              "userRate" => 0.0,
              "hasRate" => 3.0,
              "favourites" => 1,
              "favourite" => false,
              "categories" => [
                {
                  "superCategory" => {
                    "id" => "supercategory-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => nil,
                    "type" => "Supercategory",
                    "extras" => {
                      "icon" => "ic_software.svg",
                      "icon_active" => "ic_software_active.svg"
                    }
                  },
                  "subCategory" => {
                    "id" => "subcategory-other-other-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => "category-other-other",
                    "type" => "Subcategory",
                    "extras" => {
                    }
                  },
                  "category" => {
                    "id" => "category-other-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => "supercategory-other",
                    "type" => "Category",
                    "extras" => {
                      "icon" => "ic_other.svg",
                      "icon_active" => "ic_other_active.svg"
                    }
                  }
                }
              ]
            },
            {
              "service" => {
                "id" => "West-Life.metalpdb",
                "webpage" => "http://metalweb.cerm.unifi.it/",
                "name" => "MetalPDB",
                "tagline" => "",
                "description" =>
                  "Knowledge on metal sites in biological macromolecules, built on structural information in the Protein Data Bank (PDB).",
                "targetUsers" => "",
                "logo" => "http://metalweb.cerm.unifi.it/global/images/MetalPDB.png",
                "multimedia" => nil,
                "resourceOrganisation" => "bluebridge",
                "resourceProviders" => ["West-Life"],
                "version" => "1.0",
                "lastUpdate" => 1_533_513_600_000,
                "changeLog" => [""],
                "lifeCycleStatus" => "production",
                "trl" => "trl-9",
                "categories" => [{ "category" => "category-data", "subcategory" => "data-applications-software" }],
                "geographicalAvailabilities" => ["WW"],
                "languageAvailabilities" => ["EN"],
                "tags" => ["Data management", "Biochemistry"],
                "requiredResources" => [],
                "relatedResources" => [],
                "order" => "http://metalweb.cerm.unifi.it/",
                "helpdeskPage" => "https://about.west-life.eu/network/west-life/documentation",
                "userManual" => nil,
                "trainingInformation" => nil,
                "pricing" => "https://portal.phenomenal.eu/pricing",
                "paymentModel" => "http://openminted.eu/payment-model",
                "serviceLevel" => "https://auth.west-life.eu/aai/AUP.pdf",
                "termsOfUse" => "https://auth.west-life.eu/aai/AUP.pdf",
                "useCases" => nil,
                "scientificDomains" => [
                  {
                    "scientificDomain" => "scientific_domain-other",
                    "scientificSubdomain" => "scientific_subdomain-other-other"
                  }
                ],
                "accessTypes" => ["access_type-other"],
                "accessModes" => ["access_mode-other"],
                "resourceGeographicLocations" => nil,
                "mainContact" => {
                  "firstName" => "Mar",
                  "lastName" => "Sw",
                  "email" => "bbb@op.pl",
                  "phone" => "",
                  "position" => "",
                  "organisation" => ""
                },
                "publicContacts" => [
                  {
                    "firstName" => "Mar2",
                    "lastName" => "Sw2",
                    "email" => "info@bluebridge.support_for_data_publication",
                    "phone" => "",
                    "position" => "",
                    "organisation" => ""
                  }
                ],
                "helpdeskEmail" => "info@bluebridge.support_for_data_publication",
                "securityContactEmail" => "info@bluebridge.support_for_data_publication",
                "certifications" => nil,
                "standards" => nil,
                "openSourceTechnologies" => nil,
                "relatedPlatforms" => nil,
                "fundingBody" => ["funding_body-other"],
                "fundingPrograms" => ["funding_body-other"],
                "grantProjectNames" => nil,
                "privacyPolicy" => nil,
                "accessPolicy" => nil,
                "statusMonitoring" => nil,
                "orderType" => "order_type-other"
              },
              "metadata" => {
                "registeredBy" => "John Doe",
                "registeredAt" => "1549033448415",
                "modifiedBy" => "John Doe",
                "modifiedAt" => "1549624107536",
                "source" => "EOSC",
                "originalId" => nil
              },
              "geAvailabilityNames" => ["English"],
              "geographicAvailabilityNames" => ["Worldwide"],
              "trlName" => "9 - actual system proven in operational environment",
              "phaseName" => nil,
              "lifeCycleStatusName" => "Production",
              "targetUsersNames" => ["Other"],
              "accessTypeNames" => ["Other"],
              "accessModeNames" => ["Other"],
              "fundingBodyNames" => ["Other"],
              "fundingProgramNames" => nil,
              "orderTypeName" => "Other",
              "views" => 0,
              "ratings" => 0,
              "userRate" => 0,
              "hasRate" => 0,
              "favourites" => 1,
              "favourite" => false,
              "categories" => [
                {
                  "superCategory" => {
                    "id" => "supercategory-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => nil,
                    "type" => "Supercategory",
                    "extras" => {
                      "icon" => "ic_software.svg",
                      "icon_active" => "ic_software_active.svg"
                    }
                  },
                  "subCategory" => {
                    "id" => "subcategory-other-other-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => "category-other-other",
                    "type" => "Subcategory",
                    "extras" => {
                    }
                  },
                  "category" => {
                    "id" => "category-other-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => "supercategory-other",
                    "type" => "Category",
                    "extras" => {
                      "icon" => "ic_other.svg",
                      "icon_active" => "ic_other_active.svg"
                    }
                  }
                }
              ]
            },
            {
              "service" => {
                "id" => "West-Life.pdb_redo_server",
                "webpage" => "http://xtal.nki.nl/pdb_redo",
                "name" => "PDB_REDO server",
                "tagline" => "",
                "description" =>
                  "The PDB_REDO web server allows users to optimise their crystallographic structure model in an automated way. The model is refined and rebuilt in the context of the experimental data. The server returns a new structure model, new electron density maps, validation data, a script to visualise model changes in COOT, and a settings file for further model refinement in REFMAC.",
                "targetUsers" => "",
                "logo" => "https://pdb-redo.eu/images/PDB_logo_rect_medium.svg",
                "multimedia" => nil,
                "resourceOrganisation" => "bluebridge",
                "resourceProviders" => ["West-Life"],
                "version" => "6.26",
                "lastUpdate" => 1_518_912_000_000,
                "changeLog" => [""],
                "lifeCycleStatus" => "production",
                "trl" => "trl-9",
                "category" => "software",
                "categories" => [{ "category" => "category-data", "subcategory" => "data-applications-software" }],
                "geographicalAvailabilities" => ["WW"],
                "languageAvailabilities" => ["EN"],
                "tags" => ["X-ray diffraction", "Structure analysis"],
                "requiredResources" => ["super-service"],
                "relatedResources" => ["extra-service"],
                "order" => "http://xtal.nki.nl/pdb_redo",
                "helpdeskPage" => "https://about.west-life.eu/network/west-life/documentation",
                "userManual" => nil,
                "trainingInformation" => nil,
                "pricing" => nil,
                "paymentModel" => "http://openminted.eu/payment-model",
                "serviceLevel" => "https://auth.west-life.eu/aai/AUP.pdf",
                "termsOfUse" => "https://auth.west-life.eu/aai/AUP.pdf",
                "useCases" => nil,
                "scientificDomains" => [
                  {
                    "scientificDomain" => "scientific_domain-other",
                    "scientificSubdomain" => "scientific_subdomain-other-other"
                  }
                ],
                "accessTypes" => ["access_type-other"],
                "accessModes" => ["access_mode-other"],
                "resourceGeographicLocations" => nil,
                "mainContact" => {
                  "firstName" => "Mar",
                  "lastName" => "Sw",
                  "email" => "bbb@op.pl",
                  "phone" => "",
                  "position" => "",
                  "organisation" => ""
                },
                "publicContacts" => [
                  {
                    "firstName" => "Mar2",
                    "lastName" => "Sw2",
                    "email" => "info@bluebridge.support_for_data_publication",
                    "phone" => "",
                    "position" => "",
                    "organisation" => ""
                  }
                ],
                "helpdeskEmail" => "info@bluebridge.support_for_data_publication",
                "securityContactEmail" => "info@bluebridge.support_for_data_publication",
                "certifications" => nil,
                "standards" => nil,
                "openSourceTechnologies" => nil,
                "relatedPlatforms" => nil,
                "fundingBody" => ["funding_body-other"],
                "fundingPrograms" => ["funding_body-other"],
                "grantProjectNames" => nil,
                "privacyPolicy" => nil,
                "accessPolicy" => nil,
                "statusMonitoring" => nil,
                "orderType" => "order_type-other"
              },
              "metadata" => {
                "registeredBy" => "John Doe",
                "registeredAt" => "1549033448415",
                "modifiedBy" => "John Doe",
                "modifiedAt" => "1549624107536",
                "source" => "EOSC",
                "originalId" => nil
              },
              "geAvailabilityNames" => ["English"],
              "geographicAvailabilityNames" => ["Worldwide"],
              "trlName" => "9 - actual system proven in operational environment",
              "phaseName" => nil,
              "lifeCycleStatusName" => "Production",
              "targetUsersNames" => ["Other"],
              "accessTypeNames" => ["Other"],
              "accessModeNames" => ["Other"],
              "fundingBodyNames" => ["Other"],
              "fundingProgramNames" => nil,
              "orderTypeName" => "Other",
              "views" => 0,
              "ratings" => 1,
              "userRate" => 0,
              "hasRate" => 5,
              "favourites" => 1,
              "favourite" => false,
              "categories" => [
                {
                  "superCategory" => {
                    "id" => "supercategory-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => nil,
                    "type" => "Supercategory",
                    "extras" => {
                      "icon" => "ic_software.svg",
                      "icon_active" => "ic_software_active.svg"
                    }
                  },
                  "subCategory" => {
                    "id" => "subcategory-other-other-other",
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => "category-other-other",
                    "type" => "Subcategory",
                    "extras" => {
                    }
                  },
                  "category" => {
                    "id" => category,
                    "name" => "Other",
                    "description" => nil,
                    "parentId" => "supercategory-other",
                    "type" => "Category",
                    "extras" => {
                      "icon" => "ic_other.svg",
                      "icon_active" => "ic_other_active.svg"
                    }
                  }
                }
              ]
            }
          ],
          "facets" => [
            {
              "field" => "language",
              "label" => "Language",
              "values" => [
                { "value" => "albanian", "label" => "Albanian", "count" => 1 },
                { "value" => "bulgarian", "label" => "Bulgarian", "count" => 1 },
                { "value" => "danish", "label" => "Danish", "count" => 1 },
                { "value" => "greek", "label" => "Greek", "count" => 1 },
                { "value" => "french", "label" => "French", "count" => 2 },
                { "value" => "german", "label" => "German", "count" => 2 },
                { "value" => "english", "label" => "English", "count" => 154 }
              ]
            },
            {
              "field" => "subcategory",
              "label" => "Subcategory",
              "values" => [
                { "value" => "accounting", "label" => "Accounting", "count" => 1 },
                { "value" => "anonymisation", "label" => "Anonymisation", "count" => 1 },
                { "value" => "applications", "label" => "Applications", "count" => 1 },
                { "value" => "applications-software", "label" => "Applications-Software", "count" => 1 },
                { "value" => "archive", "label" => "Archive", "count" => 1 },
                { "value" => "brokering", "label" => "Brokering", "count" => 1 },
                { "value" => "business_analytics", "label" => "Business Analytics", "count" => 1 },
                { "value" => "certification_authority", "label" => "Certification Authority", "count" => 1 },
                { "value" => "data-applications-software", "label" => "Data-Applications-Software", "count" => 1 },
                { "value" => "data-publications", "label" => "Data-Publications", "count" => 1 },
                { "value" => "exchange", "label" => "Exchange", "count" => 1 },
                { "value" => "file", "label" => "File", "count" => 1 },
                { "value" => "high_performance_computing", "label" => "High Performance Computing", "count" => 1 },
                { "value" => "identity", "label" => "Identity", "count" => 1 },
                { "value" => "online_courses", "label" => "Online Courses", "count" => 1 },
                { "value" => "persistent_identifier", "label" => "Persistent Identifier", "count" => 1 },
                { "value" => "preservation", "label" => "Preservation", "count" => 1 },
                { "value" => "productivity", "label" => "Productivity", "count" => 1 },
                { "value" => "publications", "label" => "Publications", "count" => 1 },
                {
                  "value" => "services-applications-software",
                  "label" => "Services-Applications-Software",
                  "count" => 1
                },
                { "value" => "services-data", "label" => "Services-Data", "count" => 1 },
                { "value" => "services-data-publications", "label" => "Services-Data-Publications", "count" => 1 },
                { "value" => "transfer_management", "label" => "Transfer Management", "count" => 1 },
                { "value" => "validation", "label" => "Validation", "count" => 1 },
                { "value" => "virtual_machine_management", "label" => "Virtual Machine Management", "count" => 1 },
                { "value" => "web_analytics", "label" => "Web Analytics", "count" => 1 },
                { "value" => "access", "label" => "Access", "count" => 2 },
                { "value" => "coordination", "label" => "Coordination", "count" => 2 },
                { "value" => "porting", "label" => "Porting", "count" => 2 },
                { "value" => "predictive_analytics", "label" => "Predictive Analytics", "count" => 2 },
                {
                  "value" => "services-data-applications-software",
                  "label" => "Services-Data-Applications-Software",
                  "count" => 2
                },
                { "value" => "sevices-applications", "label" => "Sevices-Applications", "count" => 2 },
                { "value" => "data", "label" => "Data", "count" => 3 },
                { "value" => "direct_connect", "label" => "Direct Connect", "count" => 3 },
                { "value" => "helpdesk", "label" => "Helpdesk", "count" => 3 },
                { "value" => "interlinking", "label" => "Interlinking", "count" => 3 },
                { "value" => "monitoring", "label" => "Monitoring", "count" => 3 },
                { "value" => "software", "label" => "Software", "count" => 3 },
                { "value" => "virtual_network", "label" => "Virtual Network", "count" => 3 },
                { "value" => "job_execution", "label" => "Job Execution", "count" => 4 },
                {
                  "value" => "authentication_and_authorisation",
                  "label" => "Authentication and Authorisation",
                  "count" => 5
                },
                { "value" => "data-software-publications", "label" => "Data-Software-Publications", "count" => 5 },
                { "value" => "mining", "label" => "Mining", "count" => 5 },
                { "value" => "open_registration_courses", "label" => "Open Registration Courses", "count" => 5 },
                { "value" => "platform", "label" => "Platform", "count" => 6 },
                { "value" => "tools", "label" => "Tools", "count" => 6 },
                { "value" => "management", "label" => "Management", "count" => 7 },
                { "value" => "discovery", "label" => "Discovery", "count" => 8 },
                { "value" => "publishing", "label" => "Publishing", "count" => 9 },
                { "value" => "tool", "label" => "Tool", "count" => 16 },
                { "value" => "other", "label" => "Other", "count" => 19 }
              ]
            },
            {
              "field" => "category",
              "label" => "Category",
              "values" => [
                { "value" => "consulting", "label" => "Consulting", "count" => 2 },
                { "value" => "application", "label" => "Application", "count" => 3 },
                { "value" => "storage", "label" => "Storage", "count" => 3 },
                { "value" => "analytics", "label" => "Analytics", "count" => 4 },
                { "value" => "other", "label" => "Other", "count" => 7 },
                { "value" => "compute", "label" => "Compute", "count" => 8 },
                { "value" => "networking", "label" => "Networking", "count" => 8 },
                { "value" => "security", "label" => "Security", "count" => 11 },
                { "value" => "operations", "label" => "Operations", "count" => 12 },
                { "value" => "training", "label" => "Training", "count" => 13 },
                { "value" => "software", "label" => "Software", "count" => 19 },
                { "value" => "aggregator", "label" => "Aggregator", "count" => 23 },
                { "value" => "data", "label" => "Data", "count" => 41 }
              ]
            },
            {
              "field" => "lifeCycleStatus",
              "label" => "Lifecycle Status",
              "values" => [
                { "value" => "alpha", "label" => "Alpha", "count" => 2 },
                { "value" => "beta", "label" => "Beta", "count" => 16 },
                { "value" => "production", "label" => "Production", "count" => 136 }
              ]
            },
            {
              "field" => "providers",
              "label" => "Provider",
              "values" => [
                { "value" => "Figsharecom", "label" => "Figshare", "count" => 1 },
                { "value" => "OTC", "label" => "T-Systems International GmbH", "count" => 1 },
                { "value" => "SixSq", "label" => "SixSq", "count" => 1 },
                { "value" => "exoscale", "label" => "Exoscale", "count" => 1 },
                { "value" => "phenomenal", "label" => "Phenomenal", "count" => 1 },
                { "value" => "readcoop", "label" => "READ-COOP", "count" => 1 },
                { "value" => "vi-seem", "label" => "VI-SEEM", "count" => 1 },
                { "value" => "compbiomed", "label" => "CompBioMed", "count" => 2 },
                { "value" => "openrisknet", "label" => "OpenRiskNet", "count" => 2 },
                { "value" => "aginfra", "label" => "AGINFRA+", "count" => 6 },
                { "value" => "eudat", "label" => "EUDAT", "count" => 7 },
                { "value" => "openminted", "label" => "OpenMinTeD", "count" => 9 },
                { "value" => "prace", "label" => "PRACE", "count" => 11 },
                {
                  "value" => "West-Life",
                  "label" => "World-wide E-infrastructure for structural biology",
                  "count" => 16
                },
                { "value" => "geant", "label" => "GÉANT", "count" => 18 },
                { "value" => "openaire", "label" => "OpenAIRE", "count" => 19 },
                { "value" => "egi", "label" => "EGI Federation", "count" => 21 },
                { "value" => "bluebridge", "label" => "BlueBRIDGE", "count" => 36 }
              ]
            },
            {
              "field" => "trl",
              "label" => "TRL",
              "values" => [
                {
                  "value" => "trl-7",
                  "label" => "7 - system prototype demonstration in operational environment",
                  "count" => 17
                },
                { "value" => "trl-8", "label" => "8 - system complete and qualified", "count" => 19 },
                { "value" => "trl-9", "label" => "9 - actual system proven in operational environment", "count" => 118 }
              ]
            },
            {
              "field" => "resourceType",
              "label" => "Resource Type",
              "values" => [{ "value" => "infra_service", "label" => "Infra Service", "count" => 154 }]
            }
          ]
        }
      )
    end
  end
end
