inherit_gem:
  prettier: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
  SuggestExtensions: true
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Enabled: true
  Exclude:
    - 'app/models/jira/checker.rb'
    - 'app/models/jira/client.rb'
    - 'config/initializers/devise.rb'
    - 'db/migrate/**/*'
    - 'lib/jms/subscriber.rb'
    - 'spec/factories/jms_xml_provider.rb'
    - 'spec/factories/jms_xml_service.rb'
    - 'spec/factories/jms_service.rb'
    - 'spec/factories/jms_providers_repsonse.rb'
    - 'spec/factories/eosc_registry_vocabularies_response.rb'
    - 'spec/factories/eosc_registry_services_response.rb'
    - 'spec/factories/eosc_registry_providers_response.rb'
    - 'spec/helpers/service_helper_spec.rb'
    - 'spec/lib/jira/console_checker_spec.rb'
    - 'spec/requests/api/v1/omses/projects/project_items_controller_spec.rb'

Metrics/BlockNesting:
  Enabled: true
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 15
  Exclude:
    - 'app/models/jira/client.rb'
    - 'app/services/importers/provider.rb'
    - 'app/services/importers/service.rb'
    - 'app/services/project_item/create.rb'
    - 'app/services/service/pc_create_or_update.rb'
    - 'lib/import/vocabularies.rb'
    - 'lib/jira/console_checker.rb'

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 15
  Exclude:
    - 'app/models/jira/client.rb'
    - 'app/services/importers/provider.rb'
    - 'app/services/importers/service.rb'
    - 'app/services/service/pc_create_or_update.rb'
    - 'lib/jira/console_checker.rb'
    - 'app/services/project_item/create.rb'

Style/StringLiterals:
  Enabled: false

# Allow private methods
Lint/UselessAccessModifier:
  Enabled: false

# Allow private methods
Lint/IneffectiveAccessModifier:
  Enabled: false

# Skip if/else one liner check
Style/ConditionalAssignment:
  Enabled: false

# Turn off due error
Style/HashConversion:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

# Turn off due conflict with prettier
Style/LineEndConcatenation:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

# Interpolation thing
Style/QuotedSymbols:
  Enabled: false

# No return in ifs
Lint/NonLocalExitFromIterator:
  Enabled: false

# Expect to very small files
Metrics/ModuleLength:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Problematic
Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Require docs for each class
Style/Documentation:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

################################
# TODO Check, enable or forbid rules beneath
################################

### Large change with small impact
Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

### Beneath rules require double check before turning on
Style/RescueStandardError:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/RescueException:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/ClassVars:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

### Problematic, but worth effort

Metrics/ParameterLists:
  Enabled: false

# remove get_, has_
Naming/PredicateName:
  Enabled: false

# todo: check how to secure/replace usage of Kernel#open
Security/Open:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
