inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 3.0.2

Layout/LineLength:
  Enabled: true
  Exclude:
    - 'app/models/jira/checker.rb'
    - 'app/models/jira/client.rb'
    - 'config/initializers/devise.rb'
    - 'db/migrate/**/*'
    - 'lib/jms/subscriber.rb'
    - 'spec/factories/jms_xml_provider.rb'
    - 'spec/factories/jms_xml_service.rb'
    - 'spec/factories/jms_service.rb'
    - 'spec/factories/jms_providers_repsonse.rb'
    - 'spec/factories/eosc_registry_vocabularies_response.rb'
    - 'spec/factories/eosc_registry_services_response.rb'
    - 'spec/factories/eosc_registry_providers_response.rb'
    - 'spec/helpers/service_helper_spec.rb'
    - 'spec/lib/jira/console_checker_spec.rb'
    - 'spec/requests/api/v1/omses/projects/project_items_controller_spec.rb'

Metrics/BlockNesting:
  Enabled: true
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 15
  Exclude:
    - 'app/models/jira/client.rb'
    - 'app/services/importers/provider.rb'
    - 'app/services/importers/service.rb'
    - 'app/services/project_item/create.rb'
    - 'app/services/service/pc_create_or_update.rb'
    - 'lib/import/vocabularies.rb'
    - 'lib/jira/console_checker.rb'

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 15
  Exclude:
    - 'app/models/jira/client.rb'
    - 'app/services/importers/provider.rb'
    - 'app/services/importers/service.rb'
    - 'app/services/service/pc_create_or_update.rb'
    - 'lib/jira/console_checker.rb'
