language: ruby

rvm:
  - 2.5.1

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

addons:
  chrome: stable
  postgresql: "9.4"

services:
  - elasticsearch
  - postgresql
  - redis-server

before_script:
  # Due to google chrome bug, this is required for capybara e2e testing
  # (http://quyetbui.info/chrome-headless-capybara-on-travis-ci/)
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
  # https://docs.travis-ci.com/user/database-setup/#ElasticSearch
  - sleep 10
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml


install:
  - gem update --system
  - bundle install
  - nvm install v10.15.0
  - node -v
  - npm i -g yarn
  - yarn

stages:
  - name: test
  - name: development deploy
    if: branch = master AND type = push
  - name: production deploy
    if: branch = production AND type = push

jobs:
  include:
    - stage: test
      script:
        - bin/rails db:migrate RAILS_ENV=test
        - bundle exec rspec
    - stage: test
      script:
        - bundle exec overcommit --install
        - bundle exec overcommit --sign
        # this will not run rubocop, because there are no modified files
        - bundle exec overcommit -r
        - bundle exec rubocop
    - stage: test
      script:
        - gem install brakeman
        - brakeman --exit-on-warn --quiet -f plain

    - stage: development deploy
      install: skip
      script:
        - echo "development deploy script"
        -
    - stage: production deploy
      install: skip
      script:
        - echo "production deploy script"
