overview:
  activation_strategy: query_param

  previous:
    tour_name: "overview"
    controller_name: "home"
    action_name: "index"
    redirect_to: "root_path"
    controller_params:
      tour: overview

  next:
    tour_name: "overview"
    controller_name: "services"
    action_name: "show"
    redirect_to: "overview_tour_first_service_path"
    controller_params:
      tour: overview

  steps:
    5:
      title: Services list
      text: |-
        This page shows all the items we have in our catalogue.

        You can use the navigation at the top of the page to decide how many items you want to show on each page and whether you want to **order them by name, ranking or the best match with your profile.**

        Are you looking for something a bit more specific? The side bar can help you narrow down the selection of services.

      attachTo:
        element: "[data-shepherd-tour-target='overview_5']"
        placement: "auto"
    6:
      title: Categories
      text: |-
        The **Categories** section can help you find specific types of services.

        You can, for instance, choose to see only training materials or services to help you process and analyse data.

      attachTo:
        element: "[data-shepherd-tour-target='overview_6']"
        placement: "auto"
    7:
      title: Filters
      text: |-
        You can also **use filters** to find services that are:

        - **suited for your academic discipline**
        - **offered by specific providers**
        - **targeted at a specific group of users**
        - **related to specific infrastructures or communities**
        
        You can also limit the results based on their **rating, order type** and **accessibility.**

      attachTo:
        element: "[data-shepherd-tour-target='overview_7']"
        placement: "auto"
    8:
      title: Search bar
      text: |-
        Do you prefer to use the search bar?
        
        The **search uses** an **approximate string matching** technique that will help you find the desired service.
        Thanks to the **autocomplete function** after typing a keyword, a **list of matches will be presented**, you can go directly to the **service, provider profile**
        or be redirected to the **offer you are interested in.**        

      attachTo:
        element: "[data-shepherd-tour-target='overview_8']"
        placement: "auto"
    9:
      title: Services
      text: |-
        If you want to find out more about a specific service, you can **click to reveal more details**.

      attachTo:
        element: "[data-shepherd-tour-target='overview_9']"
        placement: "auto"
