service_about_intro:
  next:
    tour_name: "service_details_intro"
    controller_name: "details"
    action_name: "index"
    redirect_to: "service_details_path"
    controller_params_map:
      id: service_id

  steps:
    1:
      welcome: true
      title: New resource presentation layout!
      text: |-
        The resources shown in the EOSC Portal come from a wide variety of sources.
        A large number of resource attributes are being collected from providers during the resource onboarding process.

        The new layout of the resource  presentation page highlights the most necessary information,
        to ensure the presentation of a resource is helping users finding the ones, that are most relevant to their work.

    2:
      title: Main section
      text: |-
        The **main section** of the resource presentation page highlights the most important elements of the resource 
        description such as the **name**, **logotype**, list of **providers** and all the **necessary links** you will 
        need to access and use it.

      attachTo:
        element: "[data-shepherd-tour-target='service-box']"
        placement: "bottom"
    3:
      title: About
      text: |-
        The section “About” allows to analyse the resource description 
        and choose the offer appropriate for the desired use case. You will find out about:

        * **A high-level description** in fairly non-technical terms of what the service does,
          functionality it provides, resources it enables to access and the benefit to a user delivered by it
        * Information about the **resource offerings**

      attachTo:
        element: "[data-shepherd-tour-target='service-about']"
        placement: "right"
    4:
      title: Classification
      text: |-
        This section describes how the resource has been classified by the provider and who is it for. You will find out about:

        * **Scientific Classification** - the branch of science / scientific discipline that the resource is related to
        * **Categorisation** - a position in a tree-like hierarchy of resources of the same type
        * **Target users** - user groups the resource is provided for
        * **Locations** where the resource is provided
        * **Languages** supported while the resource is being delivered and used

      attachTo:
        element: "[data-shepherd-tour-target='service-classification']"
        placement: "right"
    5:
      title: More about...
      text: |-
        In order to review more advanced attributes of the resource, use the **More about...**
        link to navigate to the resource **Details** page.

      attachTo:
        element: "[data-shepherd-tour-target='service-more-about']"
        placement: "right"

