service_about_intro:
  activation_strategy: query_param
  next:
    tour_name: "service_details_intro"
    controller_name: "details"
    action_name: "index"
    redirect_to: "service_details_path"
    controller_params_map:
      id: service_id

  steps:
    1:
      welcome: true
      title: New service presentation layout!
      text: |-
        The services shown in the EOSC Portal come from a wide variety of sources.
        A large number of service attributes are being collected from providers during the service onboarding process.

        The new layout of the service  presentation page highlights the most necessary information,
        to ensure the presentation of a service is helping users finding the ones, that are most relevant to their work.
    2:
      title: Main section
      text: |-
        The **main section** of the service presentation page highlights the most important elements of the service 
        description such as the **name**, **logotype**, list of **providers** and all the **necessary links** you will 
        need to access and use it.

      attachTo:
        element: "[data-shepherd-tour-target='service-box']"
        placement: "bottom"
    3:
      title: About
      text: |-
        The section “About” allows to analyse the service description 
        and choose the offer appropriate for the desired use case. You will find out about:

        * **A high-level description** in fairly non-technical terms of what the service does,
          functionality it provides, services it enables to access and the benefit to a user delivered by it
        * Information about the **service offerings**

      attachTo:
        element: "[data-shepherd-tour-target='service-about']"
        placement: "right"
    4:
      title: Classification
      text: |-
        This section describes how the service has been classified by the provider and who is it for. You will find out about:

        * **Scientific Classification** - the branch of science / scientific discipline that the service is related to
        * **Categorisation** - a position in a tree-like hierarchy of services of the same type
        * **Target users** - user groups the service is provided for
        * **Locations** where the service is provided
        * **Languages** supported while the service is being delivered and used

      attachTo:
        element: "[data-shepherd-tour-target='service-classification']"
        placement: "right"
    5:
      title: More about...
      text: |-
        In order to review more advanced attributes of the service, use the **More about...**
        link to navigate to the service **Details** page.

      attachTo:
        element: "[data-shepherd-tour-target='service-more-about']"
        placement: "right"

overview:
  activation_strategy: query_param

  previous:
    tour_name: "overview"
    controller_name: "services"
    action_name: "index"
    redirect_to: "services_path"
    controller_params:
      tour: overview

  steps:
    10:
      title: Service details
      text: |-
        For each service, you’ll find a **short description** of the service as well as more **detailed information** such as the **maturity level of a service, contact information, accessibility** or **other services this one relies on.**

      attachTo:
        element: "[data-shepherd-tour-target='overview_10']"
        placement: "auto"
    11:
      title: Feedback ribbon
      text: |-
        Do you have feedback about the catalogue or any of the services in it? Don’t hesitate to let us know.

      attachTo:
        element: ".atlwdg-trigger"
        placement: "auto"

  feedback:
    title: Congratulations!
    text: |-
      You have completed the available services tour guide. We hope you like our presentation for new researchers and find the provided information useful.
      **Please take a moment and tell us how helpful this tour was?**
    questions:
      -
        name: rating
        type: rating
        label:
      -
        name: comment
        type: comment
        label: Please also leave a comment on how we can improve it

query_param_1:
  test: true
  activation_strategy: query_param

  next:
    tour_name: "query_param_2"
    controller_name: "details"
    action_name: "index"
    redirect_to: "service_details_path"
    controller_params:
      tour: query_param_2
    controller_params_map:
      id: service_id

  steps:
    1:
      welcome: true
      title: qp1-1 title
      text: |-
        qp1-1 text
    2:
      title: qp1-2 title
      text: |-
        qp1-2 text

      attachTo:
        element: "[data-shepherd-tour-target='service-box']"
        placement: "bottom"
