service_details_intro:
  previous:
    tour_name: "service_about_intro"
    controller_name: "services"
    action_name: "show"
    redirect_to: "service_path"
    controller_params_map:
      service_id: id

  feedback:
    title: Congratulations!
    text: |-
      You have completed the service presentation page tour guide. We hope you like our new service presentation
      layout and find the provided information useful.


      **Please take a moment and tell us how do you like the new layout of this page?**
    questions:
      -
        name: rating
        type: rating
        label:
      -
        name: comment
        type: comment
        label: Please also leave a comment on how we can improve it

  steps:
    1:
      title: Service details
      text: |-
        The **Details** page will help you to get additional information about the service.
        The details provided by service providers during the EOSC Service Onboarding
        Process will help you to assess if the service is suitable for you or not.
      attachTo:
        element: "[data-shepherd-tour-target='service-details-tab']"
        placement: "top"
    2:
      title: Service details
      text: |-
        In this summary you will find:

        * Information about the service **Classification**
        * Information about the service **Geographical Availability** and **Location**
        * **Marketing** information such as linked **Multimedia** and **Use Cases**
        * Information about **Public Contacts** for the service
        * **Maturity** Information such as **TRL**, **Life Cycle Status** or **Certification**
        * **Dependencies** - information about other services needed to use this service
        * Service attribution to **Funding Programs** and **Grants**
        * Information about **Ordering methods**
        * **Financial** Information

        If you don’t find the needed information here do not hesitate to use the '**Ask a question about this
        service**' link to ask for help. Also, consider letting the providers know in case you find some
        information missing or inaccurate.
      attachTo:
        element: "[data-shepherd-tour-target='service-details-content']"
        placement: "top"

query_param_2:
  test: true
  activation_strategy: query_param

  previous:
    tour_name: "query_param_1"
    controller_name: "services"
    action_name: "show"
    redirect_to: "service_path"
    controller_params:
      tour: query_param_1
    controller_params_map:
      service_id: id

  feedback:
    title: Congratulations!
    text: |-
      You have completed the service presentation page tour guide. We hope you like our new service presentation
      layout and find the provided information useful.


      **Please take a moment and tell us how do you like the new layout of this page?**
    questions:
      -
        name: rating
        type: rating
        label:
      -
        name: comment
        type: comment
        label: Please also leave a comment on how we can improve it

  steps:
    1:
      title: Service details
      text: |-
        The **Details** page will help you to get additional information about the service.
        The details provided by service providers during the EOSC Service Onboarding
        Process will help you to assess if the service is suitable for you or not.
      attachTo:
        element: "[data-shepherd-tour-target='service-details-tab']"
        placement: "top"
    2:
      title: Service details
      text: |-
        In this summary you will find:

        * Information about the service **Classification**
        * Information about the service **Geographical Availability** and **Location**
        * **Marketing** information such as linked **Multimedia** and **Use Cases**
        * Information about **Public Contacts** for the service
        * **Maturity** Information such as **TRL**, **Life Cycle Status** or **Certification**
        * **Dependencies** - information about other services needed to use this service
        * Service attribution to **Funding Programs** and **Grants**
        * Information about **Ordering methods**
        * **Financial** Information

        If you don’t find the needed information here do not hesitate to use the '**Ask a question about this
        service**' link to ask for help. Also, consider letting the providers know in case you find some
        information missing or inaccurate.
      attachTo:
        element: "[data-shepherd-tour-target='service-details-content']"
        placement: "top"
