default: &default
  enabled: <%= ENV["ESS_UPDATE_ENABLED"] || "false" %>
  url: <%= ENV["ESS_UPDATE_URL"] || "http://localhost:8080/batch" %>
  timeout: <%= ENV["ESS_UPDATE_TIMEOUT"] || "5" %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default