default: &default
  username: <%= ENV["MP_JIRA_USERNAME"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :username) || "''" %>
  password: <%= ENV["MP_JIRA_PASSWORD"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :password) || "''" %>
  project:  <%= ENV["MP_JIRA_PROJECT"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :project) %>
  issue_type_id: <%= ENV["MP_JIRA_ISSUE_TYPE_ID"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :issue_type_id) %>
  project_issue_type_id: <%= ENV["MP_JIRA_PROJECT_ISSUE_TYPE_ID"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :project_issue_type_id) %>
  url: <%= ENV["MP_JIRA_URL"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :url) %>
  context_path: <%= "'" + (if ENV["MP_JIRA_CONTEXT_PATH"].nil? then (Rails.application.credentials.jira.dig(Rails.env.to_sym, :context_path) || '/jira') else ENV["MP_JIRA_CONTEXT_PATH"] end) + "'" %>
  webhook_secret: <%= "'" + (if ENV["MP_JIRA_WEBHOOK_SECRET"].nil? then (Rails.application.credentials.jira.dig(Rails.env.to_sym, :webhook_secret) || '') else ENV["MP_JIRA_WEBHOOK_SECRET"] end) + "'" %>
  auth_type: basic
  # workflow specific, id of issue states should be defined here
  workflow:
    todo: <%= ENV["MP_JIRA_WF_TODO"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :todo) || 1 %>
    in_progress: <%= ENV["MP_JIRA_WF_IN_PROGRESS"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :in_progress) || 2 %>
    waiting_for_response: <%= ENV["MP_JIRA_WF_WAITING_FOR_RESPONSE"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :waiting_for_response) || 3 %>
    approved: <%= ENV["MP_JIRA_WF_APPROVED"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :approved) || 4 %>
    rejected: <%= ENV["MP_JIRA_WF_REJECTED"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :rejected) || 5 %>
    closed: <%= ENV["MP_JIRA_WF_CLOSED"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :closed) || 6 %>
    ready: <%= ENV["MP_JIRA_WF_READY"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :ready) || 7 %>
    archived: <%= ENV["MP_JIRA_WF_ARCHIVED"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :workflow, :archived) || 8 %>

  custom_fields:
    "Epic Link": <%= "'" + (ENV["MP_JIRA_FIELD_Epic_Link"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "Epic Link".to_sym) || "") + "'" %>
    "Epic Name": <%= "'" + (ENV["MP_JIRA_FIELD_Epic_Name"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "Epic Name".to_sym) || "") + "'" %>
    "Order reference": <%= "'" + (ENV["MP_JIRA_FIELD_Order_reference"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "Order reference".to_sym) || "") + "'" %>
    CI-Name: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Name"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-Name".to_sym) || "") + "'" %>
    CI-Surname: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Surname"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-Surname".to_sym) || "") + "'" %>
    CI-Email: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Email"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-Email".to_sym) || "") + "'" %>
    CI-DisplayName: <%= "'" + (ENV["MP_JIRA_FIELD_CI_DisplayName"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-DisplayName".to_sym) || "") + "'" %>
    CI-EOSC-UniqueID: <%= "'" + (ENV["MP_JIRA_FIELD_CI_EOSC_UniqueID"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-EOSC-UniqueID".to_sym) || "") + "'" %>
    CI-Institution: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Institution"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-Institution".to_sym) || "") + "'" %>
    CI-Department: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Department"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-Department".to_sym) || "") + "'" %>
    CI-DepartmentalWebPage: <%= "'" + (ENV["MP_JIRA_FIELD_CI_DepartmentalWebPage"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-DepartmentalWebPage".to_sym) || "") + "'" %>
    CI-SupervisorName: <%= "'" + (ENV["MP_JIRA_FIELD_CI_SupervisorName"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-SupervisorName".to_sym) || "") + "'" %>
    CI-SupervisorProfile: <%= "'" + (ENV["MP_JIRA_FIELD_CI_SupervisorProfile"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CI-SupervisorProfile".to_sym) || "") + "'" %>
    CP-CustomerTypology: <%= "'" + (ENV["MP_JIRA_FIELD_CP_CustomerTypology"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-CustomerTypology".to_sym) || "") + "'" %>
    CP-ReasonForAccess: <%= "'" + (ENV["MP_JIRA_FIELD_CP_ReasonForAccess"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-ReasonForAccess".to_sym) || "") + "'" %>
    CP-UserGroupName: <%= "'" + (ENV["MP_JIRA_FIELD_CP_UserGroupName"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-UserGroupName".to_sym) || "") + "'" %>
    CP-ProjectInformation: <%= "'" + (ENV["MP_JIRA_FIELD_CP_ProjectInformation"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-ProjectInformation".to_sym) || "") + "'" %>
    SO-ProjectName: <%= "'" + (ENV["MP_JIRA_FIELD_SO_ProjectName"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "SO-ProjectName".to_sym) || "") + "'" %>
    CP-ScientificDiscipline: <%= "'" + (ENV["MP_JIRA_FIELD_CP_ScientificDiscipline"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-ScientificDiscipline".to_sym) || "") + "'" %>
    CP-Platforms: <%= "'" + (ENV["MP_JIRA_FIELD_CP_Platforms"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-Platforms".to_sym) || "") + "'" %>
    CP-INeedAVoucher: <%= "'" + (ENV["MP_JIRA_FIELD_CP_INeedAVoucher"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-INeedAVoucher".to_sym) || "") + "'" %>
    CP-VoucherID: <%= "'" + (ENV["MP_JIRA_FIELD_CP_VoucherID"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-VoucherID".to_sym) || "") + "'" %>
    SO-1: <%= "'" + (ENV["MP_JIRA_FIELD_SO_1"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "SO-1".to_sym) || "") + "'" %>
    SO-ServiceOrderTarget: <%= "'" + (ENV["MP_JIRA_FIELD_SO_ServiceOrderTarget"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "SO-ServiceOrderTarget".to_sym) || "") + "'" %>
    SO-OfferType:  <%= "'" + (ENV["MP_JIRA_FIELD_SO_OfferType"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "SO-OfferType".to_sym) || "") + "'" %>
    CP-CustomerCountry: <%= "'" + (ENV["MP_JIRA_FIELD_CP_CustomerCountry"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-CustomerCountry".to_sym) || "") + "'" %>
    CP-CollaborationCountry: <%= "'" + (ENV["MP_JIRA_FIELD_CP_CollaborationCountry"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, "CP-CollaborationCountry".to_sym) || "") + "'" %>

    select_values:
      CP-CustomerTypology:
        single_user: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_single_user"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "CP-CustomerTypology".to_sym, :single_user) || "") + "'" %>
        research: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_research"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "CP-CustomerTypology".to_sym, :research) || "") + "'" %>
        private_company: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_private_company"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "CP-CustomerTypology".to_sym, :private_company) || "") + "'" %>
        project: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_project"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "CP-CustomerTypology".to_sym, :project) || "") + "'" %>
      CP-INeedAVoucher:
        'yes': <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_INeedAVoucher_true"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "CP-INeedAVoucher".to_sym, true) || "") + "'" %>
        'no': <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_INeedAVoucher_false"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "CP-INeedAVoucher".to_sym, false) || "") + "'" %>
      SO-OfferType:
        orderable: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_SO_OfferType_normal"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "SO-OfferType".to_sym, :normal) || "") + "'" %>
        open_access: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_SO_OfferType_open_access"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "SO-OfferType".to_sym, :open_access) || "") + "'" %>
        external: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_SO_OfferType_catalog"] || Rails.application.credentials.jira.dig(Rails.env.to_sym, :custom_fields, :select_values, "SO-OfferType".to_sym, :catalog) || "") + "'" %>

development:
  <<: *default

test:
  <<: *default
  issue_type_id: 10000
  project_issue_type_id: 10001
  project: "MP"
  url: "http://localhost:2990"
  context_path: "/jira"
  webhook_secret: "1234"
  workflow:
    todo: 1
    in_progress: 2
    waiting_for_response: 3
    approved: 4
    rejected: 5
    closed: 6
    ready: 7
    archived: 8

  custom_fields:
    "Epic Link": "Epic Link-1"
    "Epic Name": "Epic Name-1"
    "Order reference": "Order reference-1"
    CI-Name: "CI-Name-1"
    CI-Surname: "CI-Surname-1"
    CI-Email: "CI-Email-1"
    CI-DisplayName: "CI-DisplayName-1"
    CI-EOSC-UniqueID: "CI-EOSC-UniqueID-1"
    CI-Institution: "CI-Institution-1"
    CI-Department: "CI-Department-1"
    CI-DepartmentalWebPage: "CI-DepartmentalWebPage-1"
    CI-SupervisorName: "CI-SupervisorName-1"
    CI-SupervisorProfile: "CI-SupervisorProfile-1"
    CP-CustomerTypology: "CP-CustomerTypology-1"
    CP-ReasonForAccess: "CP-ReasonForAccess-1"
    CP-UserGroupName: "CP-UserGroupName-1"
    CP-ProjectInformation: "CP-ProjectInformation-1"
    SO-ProjectName: "SO-ProjectName-1"
    CP-ScientificDiscipline: "CP-ScientificDiscipline-1"
    CP-Platforms: "CP-Platforms-1"
    CP-INeedAVoucher: "CP-INeedAVoucher-1"
    CP-VoucherID: "CP-VoucherID-1"
    SO-1: "SO-1-1"
    SO-ServiceOrderTarget: "SO-ServiceOrderTarget-1"
    SO-OfferType: "SO-OfferType-1"
    CP-CustomerCountry: "CP-CustomerCountry-1"
    CP-CollaborationCountry: "CP-CollaborationCountry-1"

    select_values:
      CP-CustomerTypology:
        single_user: '20000'
        research: '20001'
        private_company: '20002'
      CP-INeedAVoucher:
        'yes': '20003'
        'no': '20004'
      SO-OfferType:
        orderable: '20005'
        open_access: '20006'
        external: '20007'

production:
  <<: *default
