default: &default
  username: <%= ENV["MP_JIRA_USERNAME"] || Rails.application.credentials.jira[Rails.env.to_sym][:username] || "''" %>
  password: <%= ENV["MP_JIRA_PASSWORD"] || Rails.application.credentials.jira[Rails.env.to_sym][:password] || "''" %>
  project:  <%= ENV["MP_JIRA_PROJECT"] ||  Rails.application.credentials.jira[Rails.env.to_sym][:project] %>
  issue_type_id: <%= ENV["MP_JIRA_ISSUE_TYPE_ID"] || Rails.application.credentials.jira[Rails.env.to_sym][:issue_type_id] %>
  url: <%= ENV["MP_JIRA_URL"] || Rails.application.credentials.jira[Rails.env.to_sym][:url] %>
  context_path: <%= "'" + (if ENV["MP_JIRA_CONTEXT_PATH"].nil? then (Rails.application.credentials.jira[Rails.env.to_sym][:context_path] || '/jira') else ENV["MP_JIRA_CONTEXT_PATH"] end) + "'" %>
  auth_type: basic

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default