default: &default
  username: <%= ENV["MP_JIRA_USERNAME"] || Rails.application.credentials.jira[Rails.env.to_sym][:username] || "''" %>
  password: <%= ENV["MP_JIRA_PASSWORD"] || Rails.application.credentials.jira[Rails.env.to_sym][:password] || "''" %>
  project:  <%= ENV["MP_JIRA_PROJECT"] || Rails.application.credentials.jira[Rails.env.to_sym][:project] %>
  issue_type_id: <%= ENV["MP_JIRA_ISSUE_TYPE_ID"] || Rails.application.credentials.jira[Rails.env.to_sym][:issue_type_id] %>
  url: <%= ENV["MP_JIRA_URL"] || Rails.application.credentials.jira[Rails.env.to_sym][:url] %>
  context_path: <%= "'" + (if ENV["MP_JIRA_CONTEXT_PATH"].nil? then (Rails.application.credentials.jira[Rails.env.to_sym][:context_path] || '/jira') else ENV["MP_JIRA_CONTEXT_PATH"] end) + "'" %>
  webhook_secret: <%= "'" + (if ENV["MP_JIRA_WEBHOOK_SECRET"].nil? then (Rails.application.credentials.jira[Rails.env.to_sym][:webhook_secret] || '') else ENV["MP_JIRA_WEBHOOK_SECRET"] end) + "'" %>
  auth_type: basic
  # workflow specific, id of issue states should be defined here
  workflow:
    todo: <%= ENV["MP_JIRA_WF_TODO"] || 1 %>
    in_progress: <%= ENV["MP_JIRA_WF_IN_PROGRESS"] || 2 %>
    waiting_for_response: <%= ENV["MP_JIRA_WF_WAITING_FOR_RESPONSE"] || 3 %>
    done: <%= ENV["MP_JIRA_WF_DONE"] || 4 %>
    rejected: <%= ENV["MP_JIRA_WF_REJECTED"] || 5 %>

  custom_fields:
    "Order reference": <%= "'" + (ENV["MP_JIRA_FIELD_Order_reference"] || "") + "'" %>
    CI-Name: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Name"] || "") + "'" %>
    CI-Surname: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Surname"] || "") + "'" %>
    CI-Email: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Email"] || "") + "'" %>
    CI-DisplayName: <%= "'" + (ENV["MP_JIRA_FIELD_CI_DisplayName"] || "") + "'" %>
    CI-EOSC-UniqueID: <%= "'" + (ENV["MP_JIRA_FIELD_CI_EOSC_UniqueID"] || "") + "'" %>
    CI-Institution: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Institution"] || "") + "'" %>
    CI-Department: <%= "'" + (ENV["MP_JIRA_FIELD_CI_Department"] || "") + "'" %>
    CI-DepartmentalWebPage: <%= "'" + (ENV["MP_JIRA_FIELD_CI_DepartmentalWebPage"] || "") + "'" %>
    CI-SupervisorName: <%= "'" + (ENV["MP_JIRA_FIELD_CI_SupervisorName"] || "") + "'" %>
    CI-SupervisorProfile: <%= "'" + (ENV["MP_JIRA_FIELD_CI_SupervisorProfile"] || "") + "'" %>
    CP-CustomerTypology: <%= "'" + (ENV["MP_JIRA_FIELD_CP_CustomerTypology"] || "") + "'" %>
    CP-ReasonForAccess: <%= "'" + (ENV["MP_JIRA_FIELD_CP_ReasonForAccess"] || "") + "'" %>
    CP-UserGroupName: <%= "'" + (ENV["MP_JIRA_FIELD_CP_UserGroupName"] || "") + "'" %>
    CP-ProjectInformation: <%= "'" + (ENV["MP_JIRA_FIELD_CP_ProjectInformation"] || "") + "'" %>
    SO-ProjectName: <%= "'" + (ENV["MP_JIRA_FIELD_SO_ProjectName"] || "") + "'" %>
    CP-ScientificDiscipline: <%= "'" + (ENV["MP_JIRA_FIELD_CP_ScientificDiscipline"] || "") + "'" %>
    CP-Platforms: <%= "'" + (ENV["MP_JIRA_FIELD_CP_Platforms"] || "") + "'" %>
    CP-INeedAVoucher: <%= "'" + (ENV["MP_JIRA_FIELD_CP_INeedAVoucher"] || "") + "'" %>
    CP-VoucherID: <%= "'" + (ENV["MP_JIRA_FIELD_CP_VoucherID"] || "") + "'" %>
    SO-1: <%= "'" + (ENV["MP_JIRA_FIELD_SO_1"] || "") + "'" %>

    select_values:
      CP-CustomerTypology:
        single_user: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_single_user"] || "") + "'" %>
        research: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_research"] || "") + "'" %>
        private_company: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_private_company"] || "") + "'" %>
        project: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_CustomerTypology_project"] || "") + "'" %>
      CP-INeedAVoucher:
        yes: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_INeedAVoucher_true"] || "") + "'" %>
        no: <%= "'" + (ENV["MP_JIRA_FIELD_SELECT_VALUES_CP_INeedAVoucher_false"] || "") + "'" %>

development:
  <<: *default

test:
  <<: *default
  issue_type_id: 10000
  project: "MP"
  url: "http://localhost:2990"
  context_path: "/jira"
  webhook_secret: "1234"
  workflow:
    todo: 1
    in_progress: 2
    waiting_for_response: 3
    done: 4
    rejected: 5

  custom_fields:
    "Order reference": "Order reference-1"
    CI-Name: "CI-Name-1"
    CI-Surname: "CI-Surname-1"
    CI-Email: "CI-Email-1"
    CI-DisplayName: "CI-DisplayName-1"
    CI-EOSC-UniqueID: "CI-EOSC-UniqueID-1"
    CI-Institution: "CI-Institution-1"
    CI-Department: "CI-Department-1"
    CI-DepartmentalWebPage: "CI-DepartmentalWebPage-1"
    CI-SupervisorName: "CI-SupervisorName-1"
    CI-SupervisorProfile: "CI-SupervisorProfile-1"
    CP-CustomerTypology: "CP-CustomerTypology-1"
    CP-ReasonForAccess: "CP-ReasonForAccess-1"
    CP-UserGroupName: "CP-UserGroupName-1"
    CP-ProjectInformation: "CP-ProjectInformation-1"
    SO-ProjectName: "SO-ProjectName-1"
    CP-ScientificDiscipline: "CP-ScientificDiscipline-1"
    CP-Platforms: "CP-Platforms-1"
    CP-INeedAVoucher: "CP-INeedAVoucher-1"
    CP-VoucherID: "CP-VoucherID-1"
 
    SO-1: "SO-1-1"

    select_values:
      CP-CustomerTypology:
        single_user: '20000'
        research: '20001'
        private_company: '20002'
      CP-INeedAVoucher:
        yes: '20003'
        no: '20004'

production:
  <<: *default
