:verbose: false
:concurrency: 5
:pidfile: tmp/sidekiq.pid
:logfile: log/sidekiq.log

production:
  :concurrency: 5
staging:
  :concurrency: 5

:queues:
  - jms
  - orders
  - mailers
  - reports
  - matomo
  - default
