:verbose: false
:concurrency: 5
:pidfile: tmp/sidekiq.pid
:logfile: log/sidekiq.log

production:
  :concurrency: 5
staging:
  :concurrency: 5

:queues:
  - active_storage_analysis,1
  - active_storage_purge,1
  - pc_subscriber,1
  - orders,1
  - mailers,1
  - reports,1
  - matomo,1
  - probes,1
  - default,1
  - pc_publisher,1
  - ess_update,1
  - deployments,1
  - ams_subscriber,1

:limits:
  pc_subscriber: 1
  ams_subscriber: 1

:process_limits:
  pc_subscriber: 1
  ams_subscriber: 1
