:verbose: false
:concurrency: 5
:pidfile: tmp/sidekiq.pid
:logfile: log/sidekiq.log

production:
  :concurrency: 5
staging:
  :concurrency: 5

:queues:
  - active_storage_analysis
  - active_storage_purge
  - pc_subscriber
  - orders
  - mailers
  - reports
  - matomo
  - probes
  - default
  - pc_publisher
  - ess_update

:limits:
  pc_subscriber: 1

:process_limits:
  pc_subscriber: 1
