default: &default
  client-name: <%= ENV["MP_STOMP_CLIENT_NAME"] || "'MPClient'" %>
  login: <%= ENV["MP_STOMP_LOGIN"] || Rails.application.credentials.stomp.dig(:login) || "''" %>
  password: <%= ENV["MP_STOMP_PASS"] || Rails.application.credentials.stomp.dig(:password) || "''" %>
  host: <%= ENV["MP_STOMP_HOST"] || Rails.application.credentials.stomp.dig(:host) || "''" %>
  destination: <%= ENV["MP_STOMP_DESTINATION"] || Rails.application.credentials.stomp.dig(:destination) || "''" %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
