default: &default
  client_name: <%= ENV["MP_STOMP_CLIENT_NAME"] || "'MPClient'" %>
  login: <%= ENV["MP_STOMP_LOGIN"] || Rails.application.credentials.stomp.dig(:login) || "''" %>
  password: <%= ENV["MP_STOMP_PASS"] || Rails.application.credentials.stomp.dig(:password) || "''" %>
  host: <%= ENV["MP_STOMP_HOST"] || Rails.application.credentials.stomp.dig(:host) || "''" %>
  ssl_enabled: <%= ENV["MP_STOMP_SSL"] || false %>
  topic: <%= ENV["MP_STOMP_PUBLISHER_TOPIC"] || Rails.application.credentials.stomp.dig(:publisher, :topic) || "''" %>
  mp_db_events_topic: <%= ENV["MP_STOMP_PUBLISHER_MP_DB_EVENTS_TOPIC"] || "mp_db_events" %>
  user_actions_topic: <%= ENV["MP_STOMP_PUBLISHER_USER_ACTIONS_TOPIC"] || "user_actions" %>

test:
  <<: *default
  login: <%= ENV["TEST_STOMP_LOGIN"] || "admin" %>
  password: <%= ENV["TEST_STOMP_PASS"] || "admin" %>
  host: <%= ENV["TEST_STOMP_HOST"] || "localhost" %>

development:
  <<: *default

production:
  <<: *default
