defaults: &defaults
  tour_options:
    defaultStepOptions:
      classes: theme-dark
      scrollTo: true
      arrow: true
      popperOptions: { modifiers: [{ name: 'offset', options: { offset: [30, 30] } }] }
    useModalOverlay: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
