defaults: &defaults
  tour_options:
    defaultStepOptions:
      classes: theme-dark
      scrollTo: true
      arrow: true
    useModalOverlay: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
