default: &default
  username: <%= ENV.fetch("MP_XGUS_USERNAME", "''") %>
  password: <%= ENV.fetch("MP_XGUS_PASSWORD", "''") %>
  wsdl: <%= ENV.fetch("MP_XGUS_WSDL", "''") %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default