intro2:
  previous:
    tour_name: "intro"
    action_name: "show"
    controller_name: "profiles"
    redirect_to: "root_path"
  next:
    tour_name: "intro3"
    action_name: "show"
    controller_name: "home"
  steps:
    1:
      title: "here we have..."
      text: "user categories..."
      attachTo:
        element: ".user_categories"
        placement: "right"
      buttons:
        1:
          action: 'next'
        2:
          action: 'later'
    2:
      title: "here we have...2"
      text: "user categories...2"
      attachTo:
        element: ".user_scientific_domains"
        placement: "right"
      buttons:
        1:
          action: 'next'
        2:
          action: 'later'
    3:
      title: "And the end"
      text: "thx"
      buttons:
        1:
          text: 'next'
          action: 'done'
        2:
          action: 'later'
