intro2:
  previous:
    tour_name: "intro"
    action_name: "show"
    controller_name: "profiles"
    redirect_to: "root_path"
  steps:
    1:
      title: Additional information
      text: |-
        Choose your **Category** of interests and **Research Area** of interest from the drop down list.
        It will help you to receive personalized results and updates.
      attachTo:
        element: "[data-shepherd-tour-target='profile-additional-information']"
        placement: "right"
    2:
      title: Saving changes
      text: |-
        Ince you've chosen your interests, click on the "Save changes" button to finalize your choice.
        You can modify it at any time.
      attachTo:
        element: "[data-shepherd-tour-target='profile-submit']"
        placement: "right"
    3:
      title: Great job!
      text: |-
        You have completed basic tour! We hope you liked our short introduction and this functionality
        will help you in your work.
