intro:
  steps:
    1:
      title: "WELCOME"
      text: "Welcome to your dashboard! This is where we'll highlight key information to manage your day."
    2:
      title: "Events 1"
      text:  "bla blabla bla"
      advanceOn:
        selector: ".dropdown"
        event: "click"
      attachTo:
        element: ".dropdown"
        placement: "right"
    3:
      title: "Events 1"
      text:  "bla blabla bla"
      advanceOn:
        selector: ".profile"
        event: "click"
      attachTo:
        element: ".profile"
        placement: "right"
    4:
      title: "Events 2"
      text:  "bla blabla blabla"
      advanceOn:
        selector: ".edit-button"
        action: "click"
      attachTo:
        element: ".edit-button"
        placement: "right"
    5:
      title: "Events"
      text:  "bla blabla bla pfffffff"
      attachTo:
        element: ".profile"
        placement: "right"
