name: Backend tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # ci_node values must span 1..N_GROUPS, N_GROUPS must match --only-group's -n below
      matrix:
        ci_node: [1, 2, 3, 4]

    steps:
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - uses: actions/checkout@v4
    - name: Start containers
      run: docker compose -f docker-compose-x64.yml up -d
    - name: Install VIPS
      run: sudo apt-get update && sudo apt-get install libvips -y --no-install-recommends
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'
        check-latest: true
        cache: yarn
    - run: yarn
    - name: Setup DB, Run tests
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        bundle exec rake db:drop db:create db:migrate RAILS_ENV=test
        bundle exec rake test:prepare
        bundle exec parallel_rspec -n 4 --only-group ${{ matrix.ci_node }} --group-by filesize -- -t "~end_user_frontend" -t "~manager_frontend" -- spec
    - name: Containers logs
      if: failure()
      run: docker compose logs
    - name: Stop containers
      if: always()
      run: docker compose down
