name: Integration Test with PP
on: [push]
jobs:
  e2e-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          project: ./test/system
          browser: chrome
          record: false
          command: npm run cy:run-provider-portal-integration --prefix ./test/system
        env:
          CYPRESS_JIRA_TEST_USER: ${{ secrets.JIRA_TEST_USER }}
          CYPRESS_JIRA_TEST_USER_PWD: ${{ secrets.JIRA_TEST_USER_PWD }}
          CYPRESS_MP_JIRA_URL: ${{ secrets.MP_JIRA_URL }}
          CYPRESS_MP_JIRA_PROJECT: ${{ secrets.MP_JIRA_PROJECT }}
          PROVIDER_PORTAL_REFRESH_TOKEN: ${{secrets.PROVIDER_PORTAL_REFRESH_TOKEN}}
          PROVIDER_PORTAL_URL: ${{secrets.PROVIDER_PORTAL_URL}}
          MARKETPLACE_URL: ${{secrets.MARKETPLACE_URL}}
          PROVIDER_PORTAL_CLIENT_ID: ${{secrets.PROVIDER_PORTAL_CLIENT_ID}}
          AAI_TOKEN_URL: ${{secrets.AAI_TOKEN_URL}}