name: Integration Test with PC
on: 
  workflow_dispatch
jobs:
  e2e-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ./test/system/node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('./test/system/package-lock.json') }}
      - name: Install e2e dependencies
        run: npm i --prefix ./test/system
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./test/system
          command: npm run cy:run-provider-portal-integration --prefix ./test/system
          browser: chrome
          record: false
          headless: true
          quiet: true
          install: false
        env:
          PROVIDER_PORTAL_REFRESH_TOKEN: ${{secrets.PROVIDER_PORTAL_REFRESH_TOKEN}}
          PROVIDER_PORTAL_URL: ${{secrets.PROVIDER_PORTAL_URL}}
          MARKETPLACE_URL: ${{secrets.MARKETPLACE_URL}}
          PROVIDER_PORTAL_CLIENT_ID: ${{secrets.PROVIDER_PORTAL_CLIENT_ID}}
          AAI_TOKEN_URL: ${{secrets.AAI_TOKEN_URL}}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: ./test/system/cypress/screenshots
