name: Integration Test with PC
on: 
  workflow_dispatch
jobs:
  e2e-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            ./test/system/node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('./test/system/package-lock.json') }}
      - name: Install e2e dependencies
        run: npm i --prefix ./test/system
      - name: Cypress run
        uses: cypress-io/github-action@main
        with:
          project: ./test/system
          command: npm run cy:run-provider-portal-integration --prefix ./test/system
          browser: chrome
          record: false
          headless: true
          quiet: true
          install: false
        env:
          CYPRESS_PROVIDER_PORTAL_REFRESH_TOKEN: ${{ secrets.PROVIDER_PORTAL_REFRESH_TOKEN }}
          CYPRESS_PROVIDER_PORTAL_URL: ${{ secrets.PROVIDER_PORTAL_URL }}
          CYPRESS_MARKETPLACE_URL: ${{ secrets.MARKETPLACE_URL }}
          CYPRESS_PROVIDER_PORTAL_CLIENT_ID: ${{ secrets.PROVIDER_PORTAL_CLIENT_ID }}
          CYPRESS_AAI_TOKEN_URL: ${{ secrets.AAI_TOKEN_URL }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./test/system/cypress/screenshots
