name: Rubocop
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run rubocop on changed lines
      uses: reviewdog/action-rubocop@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        rubocop_version: bundler
        reporter: github-pr-check
        fail_level: error
        filter_mode: diff_context
